### ISSUE TITLE
Automation with the Advanced Inscriber 

### ISSUE THREAD

**Issue by JustAnOkapi** [ProjectET/AE2Things#4]
When autografting the advanced inscriber does not push the presses back out when finished.

**Comment by JustAnOkapi** [comment]
> yeah i've intentionally left that out, i didnt feel that was really necessary i might add it if there is enough demand
-@ProjectET

**Comment by niXtou** [comment]
> 

Yeah that would be nice. I can't find a way to make it work with import buses or ME interfaces either.
If there was an option to lock/unlock the slots for auto-pushing, it would be great.

**Comment by LivioMirandaJr** [comment]
+1 on this

**Comment by adagadeprata** [comment]
+1 on this

**Comment by SirSebi** [comment]
yeah please add this

**Comment by Spongman** [comment]
yeah, the AE2 Stuff's Advanced Inscriber had a way to lock/unlock the press slot. without the ability to extract the press, this block doesn't add much than AE2's inscriber.

**Comment by n1ght-hunter** [comment]
+1
