### ISSUE TITLE
Grystal Growth Chamber causes server/game crash

### ISSUE THREAD

**Issue by Skyfry428** [ProjectET/AE2Things#7]
[crash-2022-02-12_00.42.32-server.txt](https://github.com/ProjectET/AE2Things/files/8054095/crash-2022-02-12_00.42.32-server.txt)

**Comment by ProjectET** [comment]
can you tell me what you were doing? And what setup you had to replicate this crash? And try the beta 2 release and see if that fixes the issue

**Comment by Skyfry428** [comment]
I had the growth chamber set up to an autocrafting setup with p2p tunnels. It was receiving energy through the bottom, items through the left side, and importing out the back into the ME system. The crash occured any time it started running.

**Comment by Skyfry428** [comment]
Seems to be fixed with the beta 2.
