### ISSUE TITLE
Lock Slot feature for Advanced Inscriber

### ISSUE THREAD

**Issue by Demsli** [ProjectET/AE2Things#8]
When connecting an exporter with printed silicon to the bottom of an advanced inscriber - all slots are filled. Ability to lock the slot for the specific input would be nice. Cause this happens:
![2022-04-15_21 48 47](https://user-images.githubusercontent.com/53137074/163625642-dc4f5772-221a-4c2b-afad-16064bb3e796.png)

**Comment by macmanad** [comment]
Replicable on with 1.0.2b2 using hopper from top or sides, or modern industrialization item cables from any face (All of Fabric 5 1.1.5)
